In [1]:
import pandas as pd 
import numpy as np 
df = pd.read_csv('foodstruct_nutritional_facts.csv')

df.nunique().sum()

np.int64(10098)

In [2]:
#valores NULOS
df.isnull().sum().sum()

np.int64(18430)

In [3]:
# Exibir as colunas
df.columns.tolist()

['Food Name',
 'Category Name',
 'Calcium',
 'Calories',
 'Carbs',
 'Cholesterol',
 'Copper',
 'Fats',
 'Fiber',
 'Folate',
 'Iron',
 'Magnesium',
 'Monounsaturated Fat',
 'Net carbs',
 'Omega-3 - DHA',
 'Omega-3 - DPA',
 'Omega-3 - EPA',
 'Phosphorus',
 'Polyunsaturated fat',
 'Potassium',
 'Protein',
 'Saturated Fat',
 'Selenium',
 'Sodium',
 'Trans Fat',
 'Vitamin A (IU)',
 'Vitamin A RAE',
 'Vitamin B1',
 'Vitamin B12',
 'Vitamin B2',
 'Vitamin B3',
 'Vitamin B5',
 'Vitamin B6',
 'Vitamin C',
 'Zinc',
 'Choline',
 'Fructose',
 'Histidine',
 'Isoleucine',
 'Leucine',
 'Lysine',
 'Manganese',
 'Methionine',
 'Phenylalanine',
 'Starch',
 'Sugar',
 'Threonine',
 'Tryptophan',
 'Valine',
 'Vitamin D',
 'Vitamin E',
 'Vitamin K',
 'Omega-3 - ALA',
 'Omega-6 - Eicosadienoic acid',
 'Omega-6 - Gamma-linoleic acid',
 'Omega-3 - Eicosatrienoic acid',
 'Omega-6 - Dihomo-gamma-linoleic acid',
 'Omega-6 - Linoleic acid',
 'Omega-6 - Arachidonic acid']

In [4]:
# Dividir colunas categoricas e num√©ricas
categoricas = df.select_dtypes(exclude = np.number)

numericas = df.select_dtypes(include = np.number)

In [5]:
categoricas.value_counts()

Food Name       Category Name
Zwieback        Baby Foods       1
100 grand bar   Sweets           1
3 musketeers    Sweets           1
Abalone         Seafood          1
Absinthe        Beverages        1
                                ..
Alaska pollock  Seafood          1
Agave nectar    Sweets           1
Agar            Vegetables       1
After eight     Sweets           1
Adzuki bean     Grains           1
Name: count, Length: 1174, dtype: int64

In [6]:
(numericas == 0).sum()

Calcium                                  47
Calories                                  8
Carbs                                   156
Cholesterol                             649
Copper                                   55
Fats                                     85
Fiber                                   352
Folate                                   99
Iron                                     44
Magnesium                                54
Monounsaturated Fat                      95
Net carbs                               156
Omega-3 - DHA                           775
Omega-3 - DPA                           770
Omega-3 - EPA                           789
Phosphorus                               55
Polyunsaturated fat                      80
Potassium                                34
Protein                                  83
Saturated Fat                            86
Selenium                                 74
Sodium                                   41
Trans Fat                               448
Vitamin A (IU)                          298
Vitamin A RAE                           354
Vitamin B1                               81
Vitamin B12                             591
Vitamin B2                               80
Vitamin B3                               67
Vitamin B5                               72
Vitamin B6                               93
Vitamin C                               467
Zinc                                     34
Choline                                  41
Fructose                                 73
Histidine                                37
Isoleucine                               34
Leucine                                  33
Lysine                                   34
Manganese                                55
Methionine                               55
Phenylalanine                            33
Starch                                   47
Sugar                                   146
Threonine                                35
Tryptophan                               54
Valine                                   34
Vitamin D                               628
Vitamin E                                82
Vitamin K                               150
Omega-3 - ALA                            11
Omega-6 - Eicosadienoic acid            174
Omega-6 - Gamma-linoleic acid           116
Omega-3 - Eicosatrienoic acid           106
Omega-6 - Dihomo-gamma-linoleic acid     70
Omega-6 - Linoleic acid                   0
Omega-6 - Arachidonic acid                0
dtype: int64

In [7]:
numericas.isnull().sum()

Calcium                                   25
Calories                                   0
Carbs                                      0
Cholesterol                               55
Copper                                    80
Fats                                       0
Fiber                                     98
Folate                                   103
Iron                                      21
Magnesium                                 61
Monounsaturated Fat                      110
Net carbs                                  1
Omega-3 - DHA                            272
Omega-3 - DPA                            279
Omega-3 - EPA                            271
Phosphorus                                48
Polyunsaturated fat                      110
Potassium                                 45
Protein                                    0
Saturated Fat                             81
Selenium                                 154
Sodium                                    21
Trans Fat                                540
Vitamin A (IU)                            56
Vitamin A RAE                            118
Vitamin B1                                59
Vitamin B12                               91
Vitamin B2                                58
Vitamin B3                                59
Vitamin B5                               199
Vitamin B6                                83
Vitamin C                                 50
Zinc                                      66
Choline                                  442
Fructose                                 872
Histidine                                465
Isoleucine                               461
Leucine                                  461
Lysine                                   453
Manganese                                162
Methionine                               456
Phenylalanine                            464
Starch                                   975
Sugar                                    300
Threonine                                462
Tryptophan                               464
Valine                                   461
Vitamin D                                345
Vitamin E                                358
Vitamin K                                383
Omega-3 - ALA                            998
Omega-6 - Eicosadienoic acid             909
Omega-6 - Gamma-linoleic acid           1004
Omega-3 - Eicosatrienoic acid           1060
Omega-6 - Dihomo-gamma-linoleic acid    1055
Omega-6 - Linoleic acid                 1033
Omega-6 - Arachidonic acid              1173
dtype: int64

In [8]:
print(string)

NameError: name 'string' is not defined

In [15]:
(df == 0).sum()

Food Name                                 0
Category Name                             0
Calcium                                  47
Calories                                  8
Carbs                                   156
Cholesterol                             649
Copper                                   55
Fats                                     85
Fiber                                   352
Folate                                   99
Iron                                     44
Magnesium                                54
Monounsaturated Fat                      95
Net carbs                               156
Omega-3 - DHA                           775
Omega-3 - DPA                           770
Omega-3 - EPA                           789
Phosphorus                               55
Polyunsaturated fat                      80
Potassium                                34
Protein                                  83
Saturated Fat                            86
Selenium                                 74
Sodium                                   41
Trans Fat                               448
Vitamin A (IU)                          298
Vitamin A RAE                           354
Vitamin B1                               81
Vitamin B12                             591
Vitamin B2                               80
Vitamin B3                               67
Vitamin B5                               72
Vitamin B6                               93
Vitamin C                               467
Zinc                                     34
Choline                                  41
Fructose                                 73
Histidine                                37
Isoleucine                               34
Leucine                                  33
Lysine                                   34
Manganese                                55
Methionine                               55
Phenylalanine                            33
Starch                                   47
Sugar                                   146
Threonine                                35
Tryptophan                               54
Valine                                   34
Vitamin D                               628
Vitamin E                                82
Vitamin K                               150
Omega-3 - ALA                            11
Omega-6 - Eicosadienoic acid            174
Omega-6 - Gamma-linoleic acid           116
Omega-3 - Eicosatrienoic acid           106
Omega-6 - Dihomo-gamma-linoleic acid     70
Omega-6 - Linoleic acid                   0
Omega-6 - Arachidonic acid                0
dtype: int64

In [27]:
for coluna in df:
    a = df[coluna].value_counts()
    print(a)

Food Name
Cherry juice     1
Acerola          1
Apple            1
Apricot          1
Dried fruit      1
                ..
Carambola        1
Breadfruit       1
Boysenberries    1
Blueberry        1
Blackberry       1
Name: count, Length: 1174, dtype: int64
Category Name
Baked Products                     106
Meat                               100
Sweets                              96
Vegetables                          90
Meals, Entrees, and Side Dishes     90
Fruits                              89
Beverages                           84
Seafood                             83
Grains                              68
Soups                               67
Greens                              60
Dairy                               58
Oils and Sauces                     54
Spices                              46
Fast Foods                          45
Nuts                                27
Mushrooms                            8
Baby Foods                           3
Name: count, dtype: int64
Calcium
0.000    47
0.010    30
0.008    29
0.018    29
0.003    28
         ..
0.233     1
0.152     1
0.368     1
0.331     1
0.733     1
Name: count, Length: 270, dtype: int64
Calories
884.0    18
43.0     12
105.0    11
32.0     11
47.0     10
         ..
526.0     1
249.0     1
308.0     1
293.0     1
478.0     1
Name: count, Length: 460, dtype: int64
Carbs
0.00     156
11.00     28
21.00     22
14.00     20
15.00     19
        ...
0.34       1
0.80       1
0.81       1
6.00       1
4.20       1
Name: count, Length: 207, dtype: int64
Cholesterol
0.000    649
0.004     15
0.002     14
0.001     14
0.005     11
        ...
0.036      1
0.165      1
0.046      1
0.037      1
0.426      1
Name: count, Length: 153, dtype: int64
Copper
0.00008    73
0.00004    59
0.00007    59
0.00005    55
0.00000    55
           ..
0.00054     1
0.00360     1
0.00064     1
0.00099     1
0.00190     1
Name: count, Length: 95, dtype: int64
Fats
0.0      85
0.1      30
14.0     26
0.2      25
100.0    23
         ..
7.3       1
6.2       1
9.9       1
5.1       1
7.8       1
Name: count, Length: 224, dtype: int64
Fiber
0.0     352
1.0      25
1.8      20
1.6      20
0.2      20
       ...
30.0      1
7.8       1
29.0      1
5.7       1
9.9       1
Name: count, Length: 118, dtype: int64
Folate
0.000000    99
0.000002    41
0.000005    40
0.000006    39
0.000001    35
            ..
0.000368     1
0.000339     1
0.000041     1
0.000176     1
0.000212     1
Name: count, Length: 187, dtype: int64
Iron
0.0000    44
0.0012    36
0.0015    33
0.0011    30
0.0016    25
          ..
0.0330     1
0.0084     1
0.0270     1
0.0054     1
0.0480     1
Name: count, Length: 196, dtype: int64
Magnesium
0.000    54
0.012    36
0.013    34
0.020    34
0.010    33
         ..
0.151     1
0.084     1
0.109     1
0.067     1
0.147     1
Name: count, Length: 171, dtype: int64
Monounsaturated Fat
0.00    95
0.01    56
0.03    37
0.02    32
0.08    21
        ..
6.60     1
4.70     1
0.89     1
0.65     1
0.59     1
Name: count, Length: 214, dtype: int64
Net carbs
0.00     156
12.00     29
15.00     19
14.00     19
16.00     19
        ...
0.17       1
0.77       1
0.30       1
7.80       1
46.00      1
Name: count, Length: 215, dtype: int64
Omega-3 - DHA
0.00     775
0.01      33
0.04       7
0.03       6
0.11       5
0.06       5
0.05       5
0.27       4
0.12       4
0.15       4
0.24       4
0.13       4
0.09       3
0.02       3
0.07       3
0.51       2
0.54       2
0.37       2
11.00      2
0.08       2
0.50       2
0.73       2
0.70       1
0.21       1
3.80       1
0.91       1
1.10       1
0.42       1
0.22       1
0.14       1
0.77       1
0.56       1
0.43       1
0.29       1
1.70       1
0.75       1
0.67       1
1.20       1
0.92       1
0.41       1
0.16       1
0.62       1
1.50       1
0.10       1
18.00      1
Name: count, dtype: int64
Omega-3 - DPA
0.00    770
0.01     51
0.02     21
0.03     12
0.04      6
0.11      5
0.09      4
0.10      3
0.06      3
0.05      2
0.17      2
0.08      2
0.07      2
0.94      1
0.23      1
0.26      1
0.14      1
0.19      1
0.22      1
0.30      1
0.21      1
0.13      1
0.18      1
3.00      1
2.00      1
Name: count, dtype: int64
Omega-3 - EPA
0.00     789
0.01      36
0.09       5
0.02       5
0.05       5
0.11       4
0.03       4
0.08       4
0.04       3
0.30       3
0.17       2
0.26       2
0.35       2
0.14       2
0.28       2
0.12       2
0.10       2
0.13       2
0.18       2
0.22       2
6.90       1
0.91       1
0.54       1
0.31       1
2.70       1
0.19       1
0.16       1
0.47       1
0.50       1
0.32       1
0.25       1
1.30       1
0.67       1
0.87       1
1.00       1
0.21       1
0.24       1
0.41       1
0.39       1
0.15       1
0.69       1
0.38       1
0.07       1
13.00      1
10.00      1
Name: count, dtype: int64
Phosphorus
0.000    55
0.020    13
0.027    13
0.024    12
0.001    12
         ..
0.467     1
1.150     1
0.316     1
0.205     1
0.137     1
Name: count, Length: 369, dtype: int64
Polyunsaturated fat
0.00    80
1.10    25
0.09    24
0.04    22
0.05    20
        ..
6.60     1
6.00     1
6.30     1
9.70     1
6.90     1
Name: count, Length: 201, dtype: int64
Potassium
0.000    34
0.002     9
0.133     8
0.001     6
0.170     6
         ..
0.189     1
0.373     1
0.298     1
0.195     1
0.596     1
Name: count, Length: 537, dtype: int64
Protein
0.00     83
11.00    31
13.00    26
14.00    24
0.07     22
         ..
7.40      1
40.00     1
0.38      1
61.00     1
6.30      1
Name: count, Length: 190, dtype: int64
Saturated Fat
0.00    86
0.03    40
0.04    34
0.02    33
0.01    29
        ..
0.60     1
8.90     1
0.72     1
0.31     1
6.60     1
Name: count, Length: 196, dtype: int64
Selenium
0.000000e+00    74
6.000000e-07    44
7.000000e-07    36
2.000000e-07    33
1.000000e-07    32
                ..
9.200000e-06     1
7.100000e-06     1
8.500000e-06     1
8.900000e-06     1
2.100000e-06     1
Name: count, Length: 155, dtype: int64
Sodium
0.001     52
0.002     43
0.000     41
0.004     37
0.005     32
          ..
0.179      1
2.193      1
1.050      1
0.993      1
38.758     1
Name: count, Length: 492, dtype: int64
Trans Fat
0.00    448
0.01     20
0.03     11
0.06     11
0.07     11
       ...
0.72      1
0.96      1
0.24      1
0.32      1
1.60      1
Name: count, Length: 63, dtype: int64
Vitamin A (IU)
0.0       298
2.0        21
1.0        15
3.0        13
5.0        12
         ...
773.0       1
1531.0      1
3066.0      1
2500.0      1
847.0       1
Name: count, Length: 463, dtype: int64
Vitamin A RAE
0.000000    354
0.000001     59
0.000002     48
0.000003     40
0.000005     18
           ...
0.000918      1
0.000740      1
0.000253      1
0.000078      1
0.001184      1
Name: count, Length: 237, dtype: int64
Vitamin B1
0.00002    93
0.00003    87
0.00000    81
0.00001    81
0.00005    60
           ..
0.00065     1
0.00180     1
0.00250     1
0.00082     1
0.00240     1
Name: count, Length: 100, dtype: int64
Vitamin B12
0.000000e+00    591
1.500000e-06     11
2.000000e-08     11
4.000000e-08     11
1.600000e-06     10
               ...
6.800000e-07      1
5.700000e-06      1
6.700000e-06      1
9.900000e-07      1
9.500000e-07      1
Name: count, Length: 150, dtype: int64
Vitamin B2
0.00000    80
0.00002    67
0.00003    67
0.00006    64
0.00004    42
           ..
0.00240     1
0.00400     1
0.00087     1
0.00210     1
0.00072     1
Name: count, Length: 95, dtype: int64
Vitamin B3
0.0000    67
0.0011    28
0.0015    25
0.0013    22
0.0016    19
          ..
0.0230     1
0.0280     1
0.0260     1
0.0081     1
0.0350     1
Name: count, Length: 197, dtype: int64
Vitamin B5
0.00000    72
0.00087    25
0.00025    21
0.00023    20
0.00038    19
           ..
0.01400     1
0.00082     1
0.00091     1
0.00094     1
0.00220     1
Name: count, Length: 126, dtype: int64
Vitamin B6
0.00000    93
0.00004    67
0.00006    55
0.00005    52
0.00008    50
           ..
0.00640     1
0.00360     1
0.00410     1
0.00270     1
0.00066     1
Name: count, Length: 103, dtype: int64
Vitamin C
0.0000    467
0.0002     28
0.0001     26
0.0007     20
0.0003     20
         ...
0.0044      1
0.0680      1
0.0099      1
0.1200      1
0.0071      1
Name: count, Length: 160, dtype: int64
Zinc
0.00110    43
0.00000    34
0.00130    21
0.00001    21
0.00100    20
           ..
0.01900     1
0.00770     1
0.01800     1
0.00810     1
0.00420     1
Name: count, Length: 176, dtype: int64
Choline
0.0000    41
0.0150    41
0.0130    25
0.0110    24
0.0120    18
          ..
0.1650     1
0.1810     1
0.0054     1
0.0420     1
0.1770     1
Name: count, Length: 190, dtype: int64
Fructose
0.00    73
1.10     8
1.50     7
2.40     6
0.07     6
        ..
0.14     1
0.36     1
0.56     1
0.73     1
0.54     1
Name: count, Length: 116, dtype: int64
Histidine
0.00001    39
0.00002    37
0.00000    37
0.00003    28
0.00004    22
           ..
0.00095     1
0.00090     1
0.00056     1
0.00091     1
0.00028     1
Name: count, Length: 101, dtype: int64
Isoleucine
0.00110    42
0.00000    34
0.00002    26
0.00130    19
0.00001    19
           ..
0.00089     1
0.00180     1
0.00044     1
0.00051     1
0.00190     1
Name: count, Length: 110, dtype: int64
Leucine
0.00000    33
0.00003    23
0.00150    20
0.00190    20
0.00200    19
           ..
0.00068     1
0.00290     1
0.00095     1
0.00097     1
0.00330     1
Name: count, Length: 124, dtype: int64
Lysine
0.00000    34
0.00003    24
0.00220    22
0.00007    21
0.00004    20
           ..
0.00082     1
0.00320     1
0.00099     1
0.00330     1
0.00062     1
Name: count, Length: 114, dtype: int64
Manganese
0.00001    88
0.00002    75
0.00000    55
0.00004    42
0.00003    26
           ..
0.00740     1
0.00075     1
0.00350     1
0.00044     1
0.00088     1
Name: count, Length: 148, dtype: int64
Methionine
0.00001    59
0.00000    55
0.00002    47
0.00004    27
0.00008    25
           ..
0.00046     1
0.00092     1
0.00087     1
0.00110     1
0.00023     1
Name: count, Length: 92, dtype: int64
Phenylalanine
0.00000    33
0.00110    26
0.00002    24
0.00004    22
0.00003    18
           ..
0.00021     1
0.00039     1
0.00180     1
0.00190     1
0.15300     1
Name: count, Length: 113, dtype: int64
Starch
0.0     47
17.0     8
15.0     7
16.0     5
26.0     4
        ..
9.8      1
71.0     1
19.0     1
31.0     1
1.8      1
Name: count, Length: 97, dtype: int64
Sugar
0.00     146
1.70      12
10.00     11
1.30      11
1.80      10
        ...
28.00      1
0.39       1
29.00      1
0.95       1
0.26       1
Name: count, Length: 224, dtype: int64
Threonine
0.00000    35
0.00110    29
0.00002    24
0.00005    24
0.00100    21
           ..
0.00056     1
0.15300     1
0.00038     1
0.00180     1
0.00040     1
Name: count, Length: 108, dtype: int64
Tryptophan
0.00001    71
0.00000    54
0.00004    46
0.00002    39
0.00005    38
0.00003    36
0.00007    31
0.00008    26
0.00011    24
0.00009    23
0.00014    21
0.00010    18
0.00027    17
0.00013    17
0.00018    15
0.00028    14
0.00026    14
0.00025    14
0.00006    14
0.00016    13
0.00023    13
0.00021    13
0.00012    13
0.00015    13
0.00029    11
0.00022    11
0.00020     9
0.00024     9
0.00017     8
0.00019     8
0.00033     7
0.00035     6
0.00031     5
0.00030     5
0.00032     4
0.00039     4
0.00037     4
0.00036     3
0.00034     3
0.00040     3
0.00038     2
0.00044     2
0.00062     1
0.00043     1
0.00042     1
0.00055     1
0.00065     1
0.15300     1
0.00046     1
0.00048     1
0.00054     1
Name: count, dtype: int64
Valine
0.00000    34
0.00130    29
0.00110    27
0.00120    27
0.00002    25
           ..
0.00200     1
0.00078     1
0.00230     1
0.00030     1
0.00240     1
Name: count, Length: 112, dtype: int64
Vitamin D
0.000000e+00    628
1.000000e-07     39
2.000000e-07     22
5.000000e-07     16
4.000000e-07     10
3.000000e-07      9
1.200000e-06      8
6.000000e-07      8
1.300000e-06      7
1.100000e-06      6
1.000000e-06      6
8.000000e-07      5
3.300000e-06      5
1.700000e-06      4
3.700000e-06      4
1.700000e-05      3
3.500000e-06      3
4.800000e-06      3
7.000000e-07      3
5.400000e-06      2
9.000000e-07      2
5.300000e-06      2
1.400000e-06      2
3.600000e-06      2
3.000000e-06      2
2.500000e-06      2
1.300000e-05      2
1.500000e-05      1
1.900000e-05      1
1.800000e-06      1
2.000000e-06      1
4.600000e-06      1
2.900000e-06      1
2.500000e-04      1
2.200000e-06      1
2.300000e-06      1
1.500000e-06      1
5.100000e-06      1
2.800000e-05      1
3.400000e-06      1
6.900000e-06      1
8.300000e-06      1
4.300000e-06      1
3.200000e-06      1
3.800000e-06      1
3.900000e-06      1
7.800000e-06      1
4.700000e-06      1
7.400000e-06      1
3.100000e-06      1
2.100000e-06      1
Name: count, dtype: int64
Vitamin E
0.00000    82
0.00001    20
0.00002    19
0.00012    18
0.00015    15
           ..
0.00380     1
0.00350     1
0.00980     1
0.00082     1
0.00370     1
Name: count, Length: 167, dtype: int64
Vitamin K
0.000000e+00    150
1.000000e-07     41
3.000000e-07     27
2.000000e-07     23
4.000000e-07     17
               ...
3.900000e-06      1
3.700000e-05      1
5.900000e-05      1
5.100000e-05      1
3.800000e-06      1
Name: count, Length: 176, dtype: int64
Omega-3 - ALA
0.02     12
0.01     12
0.00     11
0.05     10
0.08      9
0.03      7
0.06      6
0.04      6
0.16      6
0.11      5
0.24      5
0.07      5
0.13      5
0.17      5
0.15      3
0.26      3
0.12      3
0.14      3
0.62      3
0.23      3
0.21      2
0.59      2
0.18      2
0.22      2
0.52      2
0.32      2
0.36      2
0.28      2
0.77      2
0.27      2
0.45      2
0.44      2
0.09      2
0.10      2
0.37      2
18.00     1
0.79      1
5.30      1
49.00     1
0.47      1
9.10      1
2.00      1
1.90      1
0.72      1
0.89      1
0.60      1
1.00      1
0.20      1
0.49      1
0.41      1
1.50      1
0.61      1
0.38      1
0.30      1
0.43      1
0.76      1
0.64      1
0.66      1
0.84      1
Name: count, dtype: int64
Omega-6 - Eicosadienoic acid
0.00    174
0.01     58
0.02     12
0.05      5
0.03      5
0.07      3
0.04      2
0.08      2
0.14      1
0.06      1
0.20      1
0.40      1
Name: count, dtype: int64
Omega-6 - Gamma-linoleic acid
0.00    116
0.01     20
0.02     14
0.03     10
0.05      5
0.04      2
0.08      1
0.13      1
0.06      1
Name: count, dtype: int64
Omega-3 - Eicosatrienoic acid
0.00    106
0.01      5
0.02      2
0.08      1
Name: count, dtype: int64
Omega-6 - Dihomo-gamma-linoleic acid
0.00    70
0.01    36
0.02     7
0.03     4
0.04     2
Name: count, dtype: int64
Omega-6 - Linoleic acid
0.03    5
1.80    4
0.36    4
5.10    4
4.30    4
       ..
0.32    1
0.83    1
0.98    1
6.50    1
5.90    1
Name: count, Length: 87, dtype: int64
Omega-6 - Arachidonic acid
0.02    1
Name: count, dtype: int64

In [9]:
df.sample()

,Food Name,Category Name,Calcium,Calories,Carbs,Cholesterol,Copper,Fats,Fiber,Folate,...,Vitamin D,Vitamin E,Vitamin K,Omega-3 - ALA,Omega-6 - Eicosadienoic acid,Omega-6 - Gamma-linoleic acid,Omega-3 - Eicosatrienoic acid,Omega-6 - Dihomo-gamma-linoleic acid,Omega-6 - Linoleic acid,Omega-6 - Arachidonic acid
826,Green tea,Beverages,0.003,30.0,7.2,0.0,0.00001,0.18,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:

df.describe()

,Calcium,Calories,Carbs,Cholesterol,Copper,Fats,Fiber,Folate,Iron,Magnesium,...,Vitamin D,Vitamin E,Vitamin K,Omega-3 - ALA,Omega-6 - Eicosadienoic acid,Omega-6 - Gamma-linoleic acid,Omega-3 - Eicosatrienoic acid,Omega-6 - Dihomo-gamma-linoleic acid,Omega-6 - Linoleic acid,Omega-6 - Arachidonic acid
count,1149.000000,1174.000000,1174.000000,1119.000000,1094.000000,1174.000000,1076.000000,1071.000000,1153.000000,1113.000000,...,8.290000e+02,816.000000,7.910000e+02,176.000000,265.000000,170.000000,114.000000,119.000000,141.000000,1.00
mean,0.099660,224.412266,25.049940,0.030845,0.000217,10.541371,3.123885,0.000053,0.002870,0.041921,...,7.752714e-07,0.001692,2.857535e-05,0.675227,0.009321,0.008118,0.001491,0.005882,3.688936,0.02
std,0.264301,185.838852,27.222293,0.085214,0.000565,18.179044,6.383304,0.000135,0.007132,0.068221,...,8.890438e-06,0.006870,1.312185e-04,3.985335,0.031290,0.016853,0.008118,0.008773,5.342108,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,0.02
25%,0.012000,72.000000,3.600000,0.000000,0.000050,0.380000,0.000000,0.000005,0.000380,0.011000,...,0.000000e+00,0.000110,2.000000e-07,0.040000,0.000000,0.000000,0.000000,0.000000,0.620000,0.02
50%,0.031000,179.000000,13.000000,0.000000,0.000100,3.000000,1.300000,0.000017,0.001000,0.021000,...,0.000000e+00,0.000350,1.800000e-06,0.120000,0.000000,0.000000,0.000000,0.000000,1.800000,0.02
75%,0.089000,341.750000,44.750000,0.033500,0.000200,14.000000,3.200000,0.000053,0.002500,0.041000,...,0.000000e+00,0.000923,7.950000e-06,0.272500,0.010000,0.010000,0.000000,0.010000,4.700000,0.02
max,5.876000,902.000000,100.000000,1.085000,0.014000,100.000000,70.000000,0.002340,0.124000,0.770000,...,2.500000e-04,0.149000,1.715000e-03,49.000000,0.400000,0.130000,0.080000,0.040000,39.000000,0.02

In [13]:
print(df.duplicated().sum())

0